[package]
name = "mpc-curvy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "benchmark1"
path = "src/benchmarks/main.rs"

[[bin]]
name = "cli" 
path = "src/on_chain/cli/main.rs"

[dependencies]

[[test]]
name = "mpc_tests" 
path = "src/tests/mpc_tests.rs"